version: '3'

services:
  wordpress:
    image: wordpress:6.2-apache
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: mariauser
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: pagewp
    volumes:
      - wp_vol:/var/www/html
    networks:
      - wordpress_net


  database:
    image: mariadb:10.7.8
    environment:
      MYSQL_DATABASE: pagewp
      MYSQL_USER: mariauser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: mariapwd
    ports:
      - 40000:3306
    volumes:
      - db_vol:/var/lib/mysql
    networks:
      - wordpress_net


volumes:
  wp_vol:
  db_vol:

networks:
  wordpress_net:
    driver: bridge